spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      database-platform: H2
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org:
      springframework:
        data: DEBUG
        web: DEBUG
        security: DEBUG
    com:
      zero:
        account: DEBUG
    redis:
      embedded: DEBUG